from enum import Enum

DTUNKNOWN = 0
DTINTEGER = 1
DTFLOAT = 2
DTSTRING = 4
DTRASTER = 8
DTERROR = 16
DTRASTER = 32
DTTABLE = 64
DTFEATURES = 128
DTLIST = 256
DTARRAY = 512
DTBOOL = 1024
DTDICT = 2048
DTNUMBER = DTINTEGER | DTFLOAT
DTRASTERLIST = DTLIST | DTRASTER

UNDEFNUMBER = 10**20 - 1
RSUNDEF = '-1e308'

PDUNKNOWN = 0
PDUSERDEFINED = 1
PDPREDEFINED = 2
PDPROCESSGRAPH = 4

STATUSQUEUED = "queued"
STATUSCREATED = "created"
STATUSRUNNING = "running"
STATUSSTOPPED = "canceled"
STATUSFINISHED = "finished"
STATUSJOBDONE = "jobdone"
STATUSUNKNOWN = "unknown"
STATUSERROR = 'error'
CUSTOMERROR = "custom error"

ERRORPARAMETER = 'ParameterError'
ERROROPERATION = 'OperationError'

TESTFILENAME1 = 'SYNTHETIC_DATA1'
TESTFILENAME2 = 'SYNTHETIC_DATA2'
TESTFILENAME3 = 'SYNTHETIC_DATA2_MASK'

DIMSPECTRALBANDS = "DimSpectralBands"
DIMTEMPORALLAYER = "DimTemporalLayer"
DIMXYRASTER = "DimXYRaster"

METADATDEFDIM = "dimMetadata"
STRUCTUREDEFDIM = "dimStructure"
DATAIMPLEMENTATION = "rasters"





