version: '3.8'

services:
  openeo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openeo
    volumes:
      - './:/app'
      - './../data2:/app/data'
      - './../config:/app/config'
      - './../properties:/app/properties'
    #environment:
    #  - 'FLASK_DEBUG': '1'
    ports:
      - '5000:5000'
    networks:
      - 'openeo-network'

networks:
  openeo-network:
    driver: bridge
