version: '3.8'

services:
  openeo:
    user: 111:1007
    environment:
      - USER_NAME=${USER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openeo
    volumes:
      - './:/app'
      - './../data2:/app/data'
      - './../config:/app/config'
      - './../properties:/app/properties'
      - './../data2/userdata:/app/data/userdata'
      - './../temp/cache:/app/cache'
    #environment:
    #  - 'FLASK_DEBUG': '1'
    ports:
      - '5000:5000'
    networks:
      - 'openeo-network'

networks:
  openeo-network:
    driver: bridge
